evalemo/urls.py
# evalemo/urls.py
from django.conf.urls import url
from evalemo import views


app_name = 'evalemo'

urlpatterns = [

    url(r'^$', views.get_participant, name='get_participant'),  # index and participant number form 

    url(r'^goodbye/$', views.GoodbyePageView.as_view()),



    # Task B
    url(r'^evaluation/$', views.evaluation, name='evaluation'),

    url(r'^ajaxplay/$', views.ajaxplay, name='ajaxplay'),

    url(r'^instructions_eval/$', views.InstructionsEvalPageView.as_view()),

    url(r'^wasEmotion/$', views.was_emotion, name='was_emotion'),


    # Task A
    url(r'^play_comp/$', views.play_comp, name='play_comp'),

    url(r'^ajaxplay_comp/$', views.ajaxplay_comp, name='ajaxplay_comp'),




# Training

    url(r'^instructionsTR/$', views.InstructionsTRPageView.as_view()),

    url(r'^evaluationTR/$', views.tr_evaluation, name='tr_evaluation'),

    url(r'^ajaxplayTR/$', views.tr_ajaxplay, name='tr_ajaxplay'),

    url(r'^wasEmotionTR/$', views.tr_was_emotion, name='tr_was_emotion'),

]

galatea/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('evalemo.urls')),
]

evalemo/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.forms import ModelForm
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Judge(models.Model):
    trial = models.IntegerField()
    subject = models.IntegerField()
    idAnim = models.IntegerField()
    nameAnim = models.CharField(max_length=300)
    valence = models.FloatField()
    arousal = models.FloatField()
    dominance = models.FloatField()
    attention = models.IntegerField()
    was_emotion = models.IntegerField()
    # pri_emo = models.CharField(max_length=300)
    # sec_emo = models.CharField(max_length=300)
    reaction_time = models.FloatField()

    def __str__(self):
        return '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t' % (
            self.trial, self.subject, self.idAnim, self.nameAnim, self.valence, self.arousal, self.dominance,
            self.attention, self.was_emotion, self.reaction_time)


class JudgeForm(ModelForm):
    class Meta:
        model = Judge
        fields = ['trial', 'subject', 'idAnim', 'nameAnim', 'valence', 'arousal', 'dominance', 'attention', 'was_emotion',
                  'reaction_time']


@python_2_unicode_compatible
class Survey(models.Model):
    subject = models.IntegerField()
    condition = models.CharField(max_length=5)
    anth_1 = models.IntegerField()
    anth_2 = models.IntegerField()
    anth_3 = models.IntegerField()
    anth_4 = models.IntegerField()
    anth_5 = models.IntegerField()
    animacy_1 = models.IntegerField()
    animacy_2 = models.IntegerField()
    animacy_3 = models.IntegerField()
    animacy_4 = models.IntegerField()
    animacy_5 = models.IntegerField()
    animacy_6 = models.IntegerField()

    def __str__(self):
        return '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t' % (
            self.subject, self.condition, self.anth_1, self.anth_2, self.anth_3, self.anth_4, self.anth_5,
            self.animacy_1, self.animacy_2, self.animacy_3, self.animacy_4, self.animacy_5, self.animacy_6)


class SurveyForm(ModelForm):
    class Meta:
        model = Survey
        fields = ['subject', 'condition', 'anth_1', 'anth_2', 'anth_3', 'anth_4', 'anth_5', 'animacy_1', 'animacy_2',
                  'animacy_3', 'animacy_4', 'animacy_5', 'animacy_6']


@python_2_unicode_compatible
class Demographic(models.Model):
    subject = models.IntegerField(unique=True)
    age = models.IntegerField()
    sex = models.CharField(max_length=1)
    anim_experience = models.IntegerField()

    def __str__(self):
        return '%s\t%s\t%s\t%s\t' % (self.subject, self.age, self.sex, self.anim_experience)


class DemographicForm(ModelForm):
    class Meta:
        model = Demographic
        fields = ['subject', 'sex', 'age', 'anim_experience']

evalemo/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.views.generic import TemplateView
from django.http import HttpResponse
from evalemo.forms import ParticipantForm, SliderForm, WasEmotionForm, SurveyForm
from evalemo.models import Judge, Demographic, Survey
from django.http import HttpResponseRedirect
from scripts import play_df_cond_gaussian_sampling
from scripts.animDict import trials_order_tr
from scripts.anim_utils import *
from django.db import IntegrityError


naoqi_session = None
motion_ses = None
posture_ses = None
leds_ses = None
nItems = 18  # Main exp evaluation trials
nItems_tr = 3   # Training trials
n_comparisons = 2   # Godspeed trials


# Display the table Judges
def display(request):
    query_results = Judge.objects.all()
    return query_results


########## TASK 1 VIEW - COMPARISON ##################


def play_comp(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        time_submit = time.time()
        # create a form instance and populate it with data from the request:
        form = SurveyForm(request.POST)

        if form.is_valid():
            subject = request.session['subject']
            idAnim = request.session['current_anim']
            condition = idAnim
            anth_1 = int(form.cleaned_data['anth_1'])
            anth_2 = int(form.cleaned_data['anth_2'])
            anth_3 = int(form.cleaned_data['anth_3'])
            anth_4 = int(form.cleaned_data['anth_4'])
            anth_5 = int(form.cleaned_data['anth_5'])
            animacy_1 = int(form.cleaned_data['animacy_1'])
            animacy_2 = int(form.cleaned_data['animacy_2'])
            animacy_3 = int(form.cleaned_data['animacy_3'])
            animacy_4 = int(form.cleaned_data['animacy_4'])
            animacy_5 = int(form.cleaned_data['animacy_5'])
            animacy_6 = int(form.cleaned_data['animacy_6'])

            # Save demographic data in the database
            survey_obj = Survey(subject=subject, condition=condition, anth_1=anth_1, anth_2=anth_2, anth_3=anth_3,
                                anth_4=anth_4, anth_5=anth_5, animacy_1=animacy_1, animacy_2=animacy_2,
                                animacy_3=animacy_3, animacy_4=animacy_4, animacy_5=animacy_5, animacy_6=animacy_6)
            # saving all the data in the current object into the database
            survey_obj.save()
            if n_comparisons == request.session['comp_trial_count']:
                if request.session['post_exp']:
                    for sesskey in request.session.keys():
                        del request.session[sesskey]
                    return HttpResponseRedirect('/goodbye/')
                else:
                    return HttpResponseRedirect('/instructionsTR/')
            else:
                return HttpResponseRedirect('/play_comp/')
        # if a GET (or any other method) we'll create a blank form
    else:

        form = SurveyForm()

    # Comparison trial count: Which trial are we on
    request.session['comp_trial_count'] += 1
    comp_trial_count = request.session['comp_trial_count']
    print("\n=============================	Comparison trial count: " + str(comp_trial_count) + "\n")

    # The id of current anim from the permutation of the listed anims (comp_trials_list)
    request.session['current_anim'] = request.session['comp_trials_list'][comp_trial_count - 1]  # anim_order[trial_count-1]
    print("\n=============================	Current anim: " + str(request.session['current_anim']) + "\n")
    print("\n=============================	Comp_trials_list: " + str(request.session['comp_trials_list']) + "\n")
    return render(request, 'play_comp.html', {'form': form, 'flag': 1})


def ajaxplay_comp(request):

    while True:
        # Run the animation and get the name of it
        name_anim = play_df_cond_gaussian_sampling.main(motion_ses, leds_ses, request.session['current_anim'])
        print('Comp anim: ', name_anim)
        break


    return HttpResponse()


########## TASK 2 VIEW - EVALUATION ##################


def evaluation(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        time_submit = time.time()
        # create a form instance and populate it with data from the request:
        form = SliderForm(request.POST)

        if form.is_valid():
            valence = form.cleaned_data['pleasure']
            arousal = form.cleaned_data['arousal']
            dominance = form.cleaned_data['dominance']
            request.session['valence'] = valence
            request.session['arousal'] = arousal
            request.session['dominance'] = dominance
            request.session['reaction_time'] = time_submit - request.session['time_stopAnim']

            return HttpResponseRedirect('/wasEmotion/')

    # if a GET (or any other method) we'll create a blank form
    else:

        form = SliderForm()

    # Replay count: How many times th participant replays the animation
    request.session['replay_count'] = 0
    # Trial count: Which trial are we on
    request.session['trial_count'] += 1
    print("\n=============================	Trial count: " + str(request.session['trial_count']) + "\n")
    # Store the trial count and the subject to use it in the evaluation view

    form.order_fields(['pleasure', 'arousal', 'dominance'])

    trial_count = request.session['trial_count']
    subject = request.session['subject']
    request.session['current_anim'] = request.session['trials_list'][trial_count - 1]  # anim_order[trial_count-1]
    return render(request, 'AS.html',
                  {'form': form, 'flag': 1, 'state': 1})  # (state == 1) ? "/ajaxplay" : "/ajaxplayTR"


def was_emotion(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = WasEmotionForm(request.POST)
        if form.is_valid():
            attention = form.cleaned_data['attention']
            was_emotion = form.cleaned_data['likert_was_emotion']
            # pri_emo = form.cleaned_data['pri_emo']
            # sec_emo = form.cleaned_data['sec_emo']
            subject = request.session['subject']
            valence = request.session['valence']
            arousal = request.session['arousal']
            dominance = request.session['dominance']
            idAnim = request.session['current_anim']
            nameAnim = request.session['nameAnim']
            trial = request.session['trial_count']
            reaction_time = request.session['reaction_time']
            # creating a judge object containing all the data
            judge_obj = Judge(attention=attention, was_emotion=was_emotion, trial=trial, valence=valence, arousal=arousal, dominance=dominance, subject=subject,
                              idAnim=idAnim, nameAnim=nameAnim, reaction_time=reaction_time)
            # saving all the data in the current object into the database
            judge_obj.save()
            if nItems == request.session['trial_count']:
                # for sesskey in request.session.keys():
                #     del request.session[sesskey]
                # Post exp play comp
                request.session['post_exp'] = True
                request.session['comp_trial_count'] = 0
                request.session['comp_trials_list'] = np.random.permutation([30, 31]).tolist()
                return HttpResponseRedirect('/play_comp/')
                # return HttpResponseRedirect('/goodbye/')
            else:
                return HttpResponseRedirect('/evaluation/')
    else:

        form = WasEmotionForm()

    trial_count = request.session['trial_count']
    subject = request.session['subject']
    # Store the index for the next animation display
    if nItems < request.session['trial_count']:
        return HttpResponseRedirect('/play_comp/')

    return render(request, 'wasEmotion.html', {'form': form, 'flag': 1, 'state': 1})  # initial template for homepage, 'flag':1, 'state':1


def ajaxplay(request):

    while True:
        # Run the animation and get the name of it
        name_anim = play_df_cond_gaussian_sampling.main(motion_ses, leds_ses, request.session['current_anim'])
        print("Main session anim: ", name_anim)
        time_stopAnim = time.time()
        break

    # Replay button is clicked
    request.session['replay_count'] += 1
    # numPlay = request.session['replay_count']
    # # Only the first time animation is played, save the stop time
    if request.session['replay_count'] == 1:
        request.session['nameAnim'] = name_anim
        request.session['time_stopAnim'] = time_stopAnim

    return HttpResponse()


################ PARTICIPANT VIEW ################################
def get_participant(request):
    global naoqi_session
    global motion_ses
    global leds_ses

    if request.method == 'POST':
        form = ParticipantForm(request.POST)
        if form.is_valid():
            try:
                subject = form.cleaned_data['subject']
                age = form.cleaned_data['age']
                sex = form.cleaned_data['sex']
                anim_experience = form.cleaned_data['anim_experience']
                request.session['subject'] = subject
                request.session['age'] = age
                request.session['sex'] = sex
                request.session['trials_list'] = np.random.permutation(range(1, nItems + 1)).tolist()
                request.session['comp_trials_list'] = np.random.permutation([28, 29]).tolist()
                request.session['post_exp'] = False
                request.session['time_stopAnim'] = 0
                # Save demographic data in the database
                demographic_obj = Demographic(subject=subject, age=age, sex=sex, anim_experience=anim_experience)
                demographic_obj.save()
                return HttpResponseRedirect('/play_comp/')

evalemo/templates/AS.html
{% load widget_tweaks %}
<!DOCTYPE HTML>
<html>
	<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Affective Slider CRNS</title>

<style>

body {
	margin: 0px;
	padding: 50px;
}

.AffectiveSlider {
	
	width: 100%;
	text-align: center;
}

.arousal_svg {
	width: 7%;
	margin: 0px;
	margin-bottom: -30px;
}

.AffectiveSlider {
	margin-top: 2em;
}

.AffectiveSlider .intensity_cue_svg {
	width: 78%;
	position: relative;
	top: -25px;
}

@media (max-width: 1100px) {
	.AffectiveSlider .intensity_cue_svg {
		width: 76%;
		position: relative;
		top: 5px;
	}
}

input[type=range]:focus {
	outline: none;
}

.AffectiveSlider input[type=range]{
	/* fix for FF unable to apply focus style bug  */
	border: 10px solid white;

	/*required for proper track sizing in FF*/
	width: 80%;
	margin: 0px;
	padding: 0px;
	vertical-align: top;
	margin-top: 6px;
}


.AffectiveSlider input[type=range]::-moz-range-track {
	width: 100%;
	height: 20px;
	background: #ddd;
	border-radius: 10px;
	border: none;
}
input[type=range]:focus::-moz-range-track {
	background: #ccc;
}

.AffectiveSlider input[type=range]::-moz-range-thumb {
	height: 35px;
	width: 35px;
	border-radius: 60%;
	background: white;
	border: 2px solid #505050;
}

.AffectiveSlider input[type=range]::-moz-range-thumb:hover {
	background: #505050;
	border: 2px solid white;
	cursor: pointer;
	box-shadow: 0px 0px 12px #212121;
}


.AffectiveSlider input[type=range]{
	-webkit-appearance: none;
}

.statement {
	font-weight: bold;
	font-size: 28px;

}

input[type=range]::-webkit-slider-runnable-track {
	width: 100%;
	height: 20px;
	border: none;
	background: #ddd;
	border-radius: 10px;
}

input[type=range]::-webkit-slider-thumb {
	-webkit-appearance: none;
	height: 35px;
	width: 35px;
	border-radius: 60%;
	background: white;
	border: 2px solid #505050;
	margin-top: -8px;
}

.not-clicked::-webkit-slider-thumb{
  display:none;
}

input[type=range]::-webkit-slider-thumb:hover {
	background: #505050;
	border: 2px solid white;
	cursor: pointer;
	box-shadow: 0px 0px 12px #212121;
}


input[type=range]:focus::-webkit-slider-runnable-track {
	background: #ccc;
}

input[type=range]::-ms-track {
	width: 100%;
	height: 20px;
	/*remove bg colour from the track, we'll use ms-fill-lower and ms-fill-upper instead */
	background: transparent;
	/*leave room for the larger thumb to overflow with a transparent border */
	border-color: transparent;
	border-width: 16px 0;
	/*remove default tick marks*/
	color: transparent;
}
input[type=range]::-ms-fill-lower {
	background: #ddd;
	border-radius: 10px;
}
input[type=range]::-ms-fill-upper {
	background: #ddd;
	border-radius: 10px;
}
input[type=range]::-ms-thumb {
	height: 35px;
	width: 35px;
	border-radius: 60%;
	background: white;
	border: 2px solid #505050;
}
.AffectiveSlider input[type=range]::-ms-thumb:hover {
	background: #505050;
	border: 2px solid white;
	cursor: pointer;
	box-shadow: 0px 0px 12px #212121;
}
input[type=range]:focus::-ms-fill-lower {
	background: #ccc;
}
input[type=range]:focus::-ms-fill-upper {
	background: #ccc;
}

div {
	margin-bottom: 2em;
}

input[type=submit] {
    padding:5px 15px; 
    background:#ccc; 
    border:0 none;
    cursor:pointer;
    -webkit-border-radius: 5px;
    -moz-border-radius:5px;
    border-radius: 5px; 
    font-family: Tahoma;
    font-weight: bold;
    font-size: 150%;
    border-style: solid;
    font-color:#3A3738;
}

.submit {
    border-style: solid;
    border-color:#3A3738;
}

.submit:hover {
	background: -moz-linear-gradient(bottom,#ccc,#E1E0E0);
}

.play {
    position: fixed;
    left: 50px;
    bottom: 150px;
    width: 7%;
	margin: 0px;
	margin-bottom: -30px;
	outline:none;
}

</style>
</head>
<body>
{% load static %}
	<form class="AffectiveSlider" action="" method="post">

		<div id='AffectiveSlider'>
		
		{% csrf_token %}
    	{% load static %}

		{{ form.errors }}
		{{ form.non_field_errors }}
		{% for field in form.visible_fields %}
			<label class="statement" >{{ field.label }}</label>
			</br></br>
  			<div >

    			<!--<label for="{{ field.id_for_label }}">{{ field.label }}</label>-->
    			<!--{{ field | add_class:'form-control'}} {% url 'evalemo:evaluation' %}-->
    			
    			<div >
    				{% if field.name == "arousal" %}
						<object class="arousal_svg" type="image/svg+xml" data="{% static "images/ASsleepy.svg" %}"></object>
						{% render_field form.arousal type="range" class='not-clicked' min="0" max="1" step=".01" %}
    					<object class="arousal_svg" type="image/svg+xml" data="{% static "images/ASwideawake.svg" %}"></object>
    				{% elif field.name == "pleasure"%}
    					<object class="arousal_svg" type="image/svg+xml" data="{% static "images/ASunhappy.svg" %}"></object>
						{% render_field form.pleasure type="range" class='not-clicked' min="0" max="1" step=".01" %}
    					<object class="arousal_svg" type="image/svg+xml" data="{% static "images/AShappy.svg" %}"></object>
					{% else %}
    					<object class="arousal_svg" type="image/svg+xml" data="{% static "images/ASdom_low.svg" %}"></object>
						{% render_field form.dominance type="range" class='not-clicked' min="0" max="1" step=".01" %}
						<object class="arousal_svg" type="image/svg+xml" data="{% static "images/ASdom_high.svg" %}"></object>
					{% endif %}

<!--					<object class="intensity_cue_svg" type="image/svg+xml" data="{% static "images/ASintensitycue.svg" %}"></object>-->
				</div>



 			</div>
		{% endfor %}
		
		</div>


			<input id="submit_button" class="submit" type='submit' value='Submit'/>

		
	</form>
	<input id="play_button" class="play" type="image" src="{% static 'images/buttonPlay.png' %}" name="replay"/>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>

	<script src="{% static 'js/robotutils.js' %}"> </script>

	<script>

	$('.not-clicked').click(function(e){
  $(this).removeClass('not-clicked');
  $(this).addClass('clicked');
});


		 var flag = '{{flag}}';
		 // if (flag==1) {
  	// 		$("#submit_button").hide();
  	// 		}

		var state = '{{state}}'; //passed with the evaluation form 
		$(document).ready(function(){
		    $("#play_button").click(function(){
		    	$("#play_button").hide();
		    	$("#submit_button").hide();
		        
		        $.ajax({
		        	url: (state == 1) ? "/ajaxplay" : "/ajaxplayTR",
				   

				   success: function(response) {
				     	$("#play_button").show();
		    			$("#submit_button").show();
				   }
				});

		    });
		}); 
	</script>






</body>

</html>

evalemo/templates/goodbye.html
<!-- evalemo/templates/about.html -->
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>GALATEA@CRNS</title>
    <style>

html,body {padding:0;margin:0;}
.wrap {
    margin: auto;
    width: 50%;
    padding: 200px;
    font:22px Arial, san-serif;
    text-align:center;
}

.title {
    font-size: 48px
}

.bye {font-weight: bold, font-size: 30px;}

</style>
    </head>
    <body>
    {% load static %}
    <div class="wrap">
        <h1 class="title">End of the experiment</h1>
        </br>
        </br>
    <p>
	Thank you for participating!
    </p>
    </br>
    
    <h2 class="bye"> Have a great day!</h2>
    <img  type="image" src="{% static "images/menurobot.png" %}">
    </br></br>
    </div>
    </body>
</html>

evalemo/templates/index.html
<!-- evalemo/templates/index.html -->
<!DOCTYPE html>
<html>
<style>
.flex-container {
    display: -webkit-flex;
    display: flex;
    -webkit-flex-direction: column;
    -webkit-justify-content: space-around;
    align-items: center;
    flex-direction: column;
    width: 450px;
    height: 260px;
    background-color: lightgrey;
    font-weight: bold;
    margin: auto;
}

.welcome {
    display: -webkit-flex;
    display: flex;
    -webkit-flex-direction: column;
    -webkit-justify-content: space-around;
    align-items: center;
    flex-direction: column;
    width: 600px;
    height: 200px;
    margin: auto;
}

.welcome-sub {
    position: absolute;
    left: 47%;
    bottom: 40%;
    width: 10;
    text-align: center;
    font-size: 18px;

}

</style>
    <head>
        <meta charset="utf-8">
        <title>GALATEA@CRNS</title>
    </head>
    <body>
        <h1 class="welcome">Participant's Information</h1>
        <form action="{% url 'evalemo:get_participant' %}" method="post">
            
            <div class="flex-container" id="ParticipantForm">
            {% csrf_token %}
            {{ form.as_p }}
            </div>
            <input class="welcome-sub" type="submit" value="Submit">
        </form>

        
        
    </body>
</html>

evalemo/templates/instructionsA.html
<!-- evalemo/templates/about.html -->
<!DOCTYPE html>

<style>
.flex-container {
    padding: 250px;
    height: 300px;
    display: -webkit-flex;
    display: flex;
    -webkit-align-items: center;
    align-items: center;
    -webkit-justify-content: center;
    justify-content: center;
    -webkit-flex-direction: column;
    font-size: 24px;

}

.start {
    position: auto;
    left: 47%;
    bottom: 60%;
    width: 10;
    text-align: center;
    font-size: 24px;
    align-items: center;
}

.instructions-head, .instructions-body {

    -webkit-justify-content: center;
    justify-content: center;
    align-items: center;
    font-size: 30px;
}



</style>
<html>
    <head>
        <meta charset="utf-8">
        <title>GALATEA@CRNS</title>
    </head>
    <body>
    <div class="flex-container">
    <div class="instructions-head"><h1>Congratulations! You finished your training.</h1></div>
    </br>
    <p>Now you are ready to start with the main session.</p>
    <p>The rules are exactly the same as before. </p>
    <!--<p>Use the play button (bottom left of the next screen) to watch the robot's expressions.</p>
    <p>You can replay once if you need to see the expression again.</p>
    <p>After you have watched the expression, you can use the sliding bars to give your ratings: </p>
    <p>Pleasure (how negative or positive was the robot's expression) and Arousal (how tired or excited was the robot's expression).</p>
    <p>Submit when you are ready and then select the difficulty level in the scale that will appear.</p>-->
   </br>
   <p>***</p>
   <p>Dont't forget to make sure which slider is which every time!</p> 
   </br></br></br></br>
    <a class="start" href="/evaluation/">Let's start</a>
    </div>
    </body>
</html>

evalemo/templates/instructionsTR.html
<!-- evalemo/templates/about.html -->
<!DOCTYPE html>

<style>
.flex-container {
    padding: 200px;
    height: 300px;
    display: -webkit-flex;
    display: flex;
    -webkit-align-items: center;
    align-items: center;
    -webkit-justify-content: center;
    justify-content: center;
    -webkit-flex-direction: column;
    font-size: 24px;

}

.start {
    position: auto;
    left: 47%;
    bottom: 60%;
    width: 10;
    text-align: center;
    font-size: 24px;
    align-items: center;
}

.instructions-head, .instructions-body {

    -webkit-justify-content: center;
    justify-content: center;
    align-items: center;
    font-size: 30px;
}



</style>
<html>
    <head>
        <meta charset="utf-8">
        <title>GALATEA@CRNS</title>
    </head>
    <body>
    <div class="flex-container">
    </br></br></br></br>
    <div class="instructions-head"><h1>Task B - Training session</h1></div>
    </br>
    <p>As before, click the play button and watch the robot. Replay if you need to.</p>
    <p>***</p>
    <p>You will be asked to evaluate how the robot appears to feel on the following aspects:</p>
        <ul>
            <li><b>Displeased - Pleased:</b> How negative or positive the robot appears to feel? </li></br>
            <li><b>Inactive - Active:</b> How drowsy or alert the robot appears to feel? </li></br>
            <li><b>Submissive - Dominant:</b> Does the robot appear to feel vulnerable or strong?</li>

        </ul>

    </br></br>
    <a class="start" href="/evaluationTR/">Let's start</a>
    </div>
    </body>
</html>

evalemo/templates/instructions_eval.html
<!-- evalemo/templates/about.html -->
<!DOCTYPE html>

<style>
.flex-container {
    padding: 250px;
    height: 300px;
    display: -webkit-flex;
    display: flex;
    -webkit-align-items: center;
    align-items: center;
    -webkit-justify-content: center;
    justify-content: center;
    -webkit-flex-direction: column;
    font-size: 24px;

}

.start {
    position: auto;
    left: 47%;
    bottom: 60%;
    width: 10;
    text-align: center;
    font-size: 24px;
    align-items: center;
}

.instructions-head, .instructions-body {

    -webkit-justify-content: center;
    justify-content: center;
    align-items: center;
    font-size: 30px;
}



</style>
<html>
    <head>
        <meta charset="utf-8">
        <title>GALATEA@CRNS</title>
    </head>
    <body>
    <div class="flex-container">
    <div class="instructions-head"><h1>Congratulations!</h1></div>
    </br>
    <p>You finished your training. Now you are ready to start with the main session of Task B.</p>

   </br>
   <p>***</p>

   </br></br></br></br>
    <a class="start" href="/evaluation/">Let's start</a>
    </div>
    </body>
</html>